// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghetfnfcvoqxabltirzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZXRmbmZjdm9xeGFibHRpcnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Njc2MjcsImV4cCI6MjA3NDU0MzYyN30.Ws9NkNyNEoQy0FVNh_rGfGGFeei4kxsn2EmW5SwlMMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});